services:
  mysql:
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    container_name: citizen-services-mysql
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: citizen-services-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-5000}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-citizen_services}
      DB_USER: ${DB_USER:-citizen_user}
      DB_PASSWORD: ${DB_PASSWORD:-citizen_password}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      FRONTEND_URL: ${FRONTEND_URL:-https://frontend}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: citizen-services-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    container_name: citizen-services-nginx
    restart: always
    ports:
      - "8000:80"
      - "44300:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
      - ./certificate.crt:/etc/nginx/certs/certificate.crt
      - ./ec-private-key.pem:/etc/nginx/certs/ec-private-key.pem
      - ./ca_bundle.crt:/etc/nginx/certs/ca_bundle.crt
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    name: citizen_services_mysql_data
  backend_node_modules:
    name: citizen_services_backend_node_modules
  frontend_node_modules:
    name: citizen_services_frontend_node_modules
  frontend_dist:
    name: citizen_services_frontend_dist
