services:
  mysql:
    image: mysql:8.0
    container_name: citizen-services-mysql
    restart: always
    env_file:
      - ./backend/.env
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: citizen-services-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=mysql
      - DB_PORT=3306
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: citizen-services-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: citizen-services-nginx
    restart: always
    ports:
      - "8000:80"
      - "44300:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./certificate.crt:/etc/nginx/certs/certificate.crt
      - ./ec-private-key.pem:/etc/nginx/certs/ec-private-key.pem
      - ./ca_bundle.crt:/etc/nginx/certs/ca_bundle.crt
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  backend_node_modules:

  frontend_node_modules: