FROM mysql:8.0.40

# Copy initialization scripts
COPY database/init.sql /docker-entrypoint-initdb.d/01-init.sql
COPY database/seed.sql /docker-entrypoint-initdb.d/02-seed.sql
COPY database/entrypoint.sh /docker-entrypoint-initdb.d/entrypoint.sh

# Set permissions
RUN chmod +x /docker-entrypoint-initdb.d/entrypoint.sh
RUN chown -R mysql:mysql /var/lib/mysql

EXPOSE 3306